CREATE TABLE "AT_MV" 
(	"NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"QUERY_SELECT" VARCHAR2(2048 BYTE) NOT NULL ENABLE,
	"QUERY_MERGE" VARCHAR2(2048 BYTE) NOT NULL ENABLE,
	"ORDER_NUMBER" NUMBER(2,0), 
	"ENABLED" NUMBER(1,0), 
	CONSTRAINT "AT_MV_PK" PRIMARY KEY ("NAME") ENABLE
);


CREATE TABLE "AT_TABLE_LOG" 
(	"IDENTIFIER" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"ACTOR" VARCHAR2(1024 BYTE) NOT NULL ENABLE,  
	"ACTION" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"INPUTS" VARCHAR2(1024 BYTE), 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"OUTPUTS" VARCHAR2(1024 BYTE), 
	"EXCEPTION" VARCHAR2(1024 BYTE), 
	 CONSTRAINT "AT_TABLE_LOG_PK" PRIMARY KEY ("IDENTIFIER") ENABLE
);


CREATE TABLE "AT_MV_SCRIPT" 
(	"MV" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SCRIPT" VARCHAR2(2048 BYTE) NOT NULL ENABLE, 
	"ORDER_NUMBER" NUMBER(2,0),
	"ENABLED" NUMBER(1,0), 
	 CONSTRAINT "AT_MV_SCRIPT_FK1" FOREIGN KEY ("MV") REFERENCES "AT_MV" ("NAME") ENABLE
);