INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','1');
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('1','1','1','1',1);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE_BUDGETAIRE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('1','1','1','1',0,0);