INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','1');
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('1','1','1','1',1);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('1','1','1','1','1','1',0,0);
-- identifier not exist
-- identifier available not enough
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('identifier_available_not_enough','1','1','1','1','1',0,0);
INSERT into VA_LIGNE_DEPENSE (IDENTIFIANT,BUDGET_INITIAL_AE,BUDGET_INITIAL_CP,BUDGET_ACTUEL_AE,BUDGET_ACTUEL_CP,DISPONIBLE_AE,DISPONIBLE_CP) values ('identifier_available_not_enough',0,0,0,0,0,0);
