INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('A001','A001','Acte 2021');
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('V001','V001','Version 001','A001',1);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('1','1','1','1','1','V001',0,0);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('2','1','1','1','1','V001',3,0);

INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','Personnel');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','2','Biens e services');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','3','Investissement');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('4','4','Transfert');

INSERT INTO VA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('101','101','Assemblée Nationale');
INSERT INTO VA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('327','327','Budget');
INSERT INTO VA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('323','323','Intérieur');