INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','Personnel');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','2','Biens e services');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','3','Investissement');
INSERT INTO VA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('4','4','Transfert');

INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('AB01','AB01','1');
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('VAB01_01','VAB01_01','Version 01','AB01',1);

INSERT INTO VA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('S01','S01','Section 01');
INSERT INTO VA_USB(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT) VALUES ('USB01','USB01','USB 01','S01');
INSERT INTO VA_ACTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('S01','S01','Section 01');

INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('1','1','1','1','1','VAB01_01',0,0);
INSERT INTO VA_LIGNE_DEPENSE(IDENTIFIANT,BUDGET_INITIAL_AE,BUDGET_ACTUEL_AE,MOUVEMENT_AE,DISPONIBLE_AE) VALUES ('1',1,2,3,4);

-- update entry authorization : one
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_one_01','1','1','1','1','VAB01_01',0,0);
-- update entry authorization : many
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_many_01','1','1','1','1','VAB01_01',0,0);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_ACTE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_many_02','1','1','1','1','VAB01_01',-2,0);