INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','1');
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('1','1','1','1',1);

INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE_BUDGETAIRE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('1','1','1','1',0,0);

-- update entry authorization : one
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE_BUDGETAIRE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_one_01','1','1','1',0,0);
-- update entry authorization : many
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE_BUDGETAIRE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_many_01','1','1','1',0,0);
INSERT INTO TA_LIGNE_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE_BUDGETAIRE,AJUSTEMENT_AE,AJUSTEMENT_CP) VALUES ('uea_many_02','1','1','1',-2,0);