INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','01','Budget Général');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','02','Budget Annexe');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','03','Comptes Spéciaux du Trésor');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('4','11','Budget des Institutions');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('5','12','Budget des Collectivités Territoriales Décentralisées');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('6','13','Budget des Etablissements Publics Nationaux');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('7','14','Budget des représentations nationnales à l''étranger');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('8','15','Budget de COGES');
INSERT INTO VMA_CATEGORIE_BUDGET(IDENTIFIANT,CODE,LIBELLE) VALUES ('9','16','Budget des projets en transferts');

INSERT INTO VMA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','101','Assemblée Nationale');
INSERT INTO VMA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','327','Minitère du Budget');
INSERT INTO VMA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','348','Minitère du pétrole');

INSERT INTO VMA_USB(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','22001','Prog 01');
INSERT INTO VMA_USB(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','22002','Prog 02');
INSERT INTO VMA_USB(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','22003','Prog 03');

INSERT INTO VMA_ACTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','220010','Action 01');
INSERT INTO VMA_ACTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','220020','Action 02');
INSERT INTO VMA_ACTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','220030','Action 03');
