INSERT INTO VMA_EXERCICE(IDENTIFIANT,CODE,LIBELLE,ANNEE) VALUES ('2021','2021','Exercice budgétaire 2021',2021);
INSERT INTO VMA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','Personnel');
INSERT INTO VMA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('2','2','Biens e services');
INSERT INTO VMA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('3','3','Investissement');
INSERT INTO VMA_NATURE_DEPENSE(IDENTIFIANT,CODE,LIBELLE) VALUES ('4','4','Transfert');

INSERT INTO VMA_NATURE_ECONOMIQUE(IDENTIFIANT,CODE,LIBELLE) VALUES ('1','1','Nature Eco 01');

INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('AB01','AB01','1','2021','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,COLLECTIF,NUMERO,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('VAB01_01','VAB01_01','Version 01','AB01',1,'christian','CREATION', DATE '2000-1-1','CREATION');

INSERT INTO VMA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('S01','S01','Section 01');
INSERT INTO VMA_USB(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT) VALUES ('USB01','USB01','USB 01','S01');
INSERT INTO VMA_ACTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('S01','S01','Section 01');

INSERT INTO TA_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_COLLECTIF,AJUSTEMENT_AE,AJUSTEMENT_CP,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('1','activity01','1','1','1','VAB01_01',0,0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO VMA_DEPENSE(IDENTIFIANT,BUDGET_INITIAL_AE,BUDGET_ACTUEL_AE) VALUES ('1',1,2);
INSERT INTO VA_DEPENSE_DISPONIBLE(IDENTIFIANT,AE) VALUES ('1',4);

INSERT INTO VMA_ACTIVITE(IDENTIFIANT,CODE,LIBELLE,NATURE_DEPENSE_IDENTIFIANT,NATURE_DEPENSE_CODE,NATURE_DEPENSE_CODE_LIBELLE,SECTION_IDENTIFIANT,SECTION_CODE,SECTION_CODE_LIBELLE,USB_IDENTIFIANT,USB_CODE,USB_CODE_LIBELLE,ACTION_IDENTIFIANT,ACTION_CODE,ACTION_CODE_LIBELLE) 
VALUES ('activity01','activity01','activity 01','2','2','2 Biens et services','S01','S01','S01 Section 01','USB01','USB01','USB01 USB 01','A01','A01','A01 Action 01');

-- update entry authorization : one
INSERT INTO TA_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_COLLECTIF,AJUSTEMENT_AE,AJUSTEMENT_CP,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('uea_one_01','activity01','2','1','1','VAB01_01',0,0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
-- update entry authorization : many
INSERT INTO TA_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_COLLECTIF,AJUSTEMENT_AE,AJUSTEMENT_CP,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('uea_many_01','activity01','3','1','1','VAB01_01',0,0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_DEPENSE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,SOURCE_FINANCEMENT,BAILLEUR,VERSION_COLLECTIF,AJUSTEMENT_AE,AJUSTEMENT_CP,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('uea_many_02','activity01','4','1','1','VAB01_01',-2,0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');