INSERT INTO TA_ACTE(IDENTIFIANT,CODE,LIBELLE,EXERCICE) VALUES ('1','1','Collectif budgétaire 2021',2021);
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('1','1','Version 1 du Collectif budgétaire 2021','1',1);
INSERT INTO TA_VERSION_ACTE(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('2','2','Version 2 du Collectif budgétaire 2021','1',2);