DROP ALIAS IF EXISTS PA_EXECUTER_PROCEDURE;
CREATE ALIAS PA_IMPORTER_DEPENSE FOR "ci.gouv.dgbf.system.collectif.server.impl.Procedures.PA_IMPORTER_DEPENSE";

INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE,EN_COURS) VALUES ('2021_1','2021_1','Collectif Budgétaire 2021 du 01/01/2021','2021','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT',1);