INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('1','1','Collectif Budgétaire 2021 du 01/01/2021',2021,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO,DATE_CREATION) VALUES ('1_1','1_1','Version du Collectif Budgétaire 2021 du 01/01/2021','1',1, DATE '2021-01-01');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO,DATE_CREATION) VALUES ('1_2','1_2','2','1',2, DATE '2021-01-01');

INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2','2','Collectif Budgétaire 2021 du 01/07/2021',2021,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO,DATE_CREATION) VALUES ('2_1','2_1','1','2',1, DATE '2021-01-01');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO,DATE_CREATION) VALUES ('2_2','2_2','2','2',2, DATE '2021-01-01');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO,DATE_CREATION) VALUES ('2_3','2_3','3','2',3, DATE '2021-01-01');

INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('3','3','Collectif Budgétaire 2021 du 01/03/2022',2022,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');

INSERT INTO TA_ACTE_GENERE(IDENTIFIANT,CODE,LIBELLE,VERSION_COLLECTIF,TYPE,ACTE_SOURCE,APPLIQUE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('1','1','1','2_1','AJUSTEMENT','2',0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');