DROP ALIAS IF EXISTS AP_ACTUALIZE_MV;
CREATE ALIAS AP_ACTUALIZE_MV FOR "ci.gouv.dgbf.system.collectif.server.impl.ResourceTest.PA_ACTUALISER_VM";

INSERT INTO VMA_EXERCICE(IDENTIFIANT,CODE,LIBELLE,ANNEE) VALUES ('2021','2021','Exercice budgétaire 2021',2021);
INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE,EN_COURS,NUMERO,DATE_) VALUES ('2021_1','2021_1','2021_1','2021','1','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT',1,1, DATE '2000-1-1');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,COLLECTIF,NUMERO,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_1','2021_1_1','2021_1_1','2021_1',1,'1','christian','CREATION', DATE '2000-1-1','CREATION');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,COLLECTIF,NUMERO,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_2','2021_1_2','2021_1_2','2021_1',2,'1','christian','CREATION', DATE '2000-1-1','CREATION');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,COLLECTIF,NUMERO,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_running','2021_1_running','2021_1_running','2021_1',3,'1','christian','CREATION', DATE '2000-1-1','CREATION');

INSERT INTO TA_RESSOURCE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_COLLECTIF,AJUSTEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_1_1','A1','NE1','2021_1_1',3,'1','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
--INSERT INTO VMA_RESSOURCE(IDENTIFIANT,BUDGET_INITIAL,BUDGET_ACTUEL) VALUES ('2021_1_1_1',1,2);
INSERT INTO VMA_RESSOURCE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT,BUDGET_INITIAL,MOUVEMENT,BUDGET_ACTUEL) VALUES ('2021_1_1_1','2021_1_1','A1','NE1',1,2,3);
INSERT INTO TA_RESSOURCE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_COLLECTIF,AJUSTEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_1_2','A2','NE1','2021_1_1',0,'1','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_RESSOURCE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_COLLECTIF,AJUSTEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_1_3','A3','NE1','2021_1_1',0,'1','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_RESSOURCE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_COLLECTIF,AJUSTEMENT,AUDIT_IDENTIFIANT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2021_1_1_4','A4','NE1','2021_1_1',0,'1','christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');

INSERT INTO VMA_NATURE_ECONOMIQUE(IDENTIFIANT,CODE,LIBELLE) VALUES ('NE1','NE1','NE1');
INSERT INTO VMA_SECTION(IDENTIFIANT,CODE,LIBELLE) VALUES ('S1','S1','S1');
INSERT INTO VMA_USB(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT) VALUES ('USB1','USB1','USB1','S1');
INSERT INTO VMA_ACTIVITE_RESSOURCE(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT,SECTION_CODE,SECTION_CODE_LIBELLE,USB_IDENTIFIANT,USB_CODE,USB_CODE_LIBELLE) VALUES ('A1','A1','A1','S1','S1','S1','USB1','USB1','USB1');
INSERT INTO VMA_ACTIVITE_RESSOURCE(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT,SECTION_CODE,SECTION_CODE_LIBELLE,USB_IDENTIFIANT,USB_CODE,USB_CODE_LIBELLE) VALUES ('A2','A2','A2','S1','S1','S1','USB1','USB1','USB1');
INSERT INTO VMA_ACTIVITE_RESSOURCE(IDENTIFIANT,CODE,LIBELLE,SECTION_IDENTIFIANT,SECTION_CODE,SECTION_CODE_LIBELLE,USB_IDENTIFIANT,USB_CODE,USB_CODE_LIBELLE) VALUES ('A3','A3','A3','S1','S1','S1','USB1','USB1','USB1');

INSERT INTO VA_RESSOURCE_IMPORTABLE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT) VALUES ('2021_1_2_1','2021_1_2','1','1');
INSERT INTO VA_RESSOURCE_IMPORTABLE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT) VALUES ('2021_1_2_2','2021_1_2','2','1');
INSERT INTO VA_RESSOURCE_IMPORTABLE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT) VALUES ('2021_1_2_3','2021_1_2','3','1');
INSERT INTO VA_RESSOURCE_IMPORTABLE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT) VALUES ('2021_1_2_4','2021_1_2','4','1');
INSERT INTO VA_RESSOURCE_IMPORTABLE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT) VALUES ('2021_1_2_5','2021_1_2','5','1');

--INSERT INTO VMA_RESSOURCE(IDENTIFIANT,VERSION_COLLECTIF,ACTIVITE_IDENTIFIANT,NATURE_ECONOMIQUE_IDENTIFIANT,BUDGET_INITIAL,MOUVEMENT,BUDGET_ACTUEL) VALUES ('2021_1_1_1','2021_1_1','A1','NE1',1,2,3);
