INSERT INTO TA_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,EXERCICE,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('1','1','1',2021,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_VERSION_COLLECTIF(IDENTIFIANT,CODE,LIBELLE,ACTE,NUMERO) VALUES ('1','1','1','1',1);
INSERT INTO TA_LIGNE_RECETTE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE,AJUSTEMENT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('1','1','1','1',0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
INSERT INTO TA_LIGNE_RECETTE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE,AJUSTEMENT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('2','2','1','1',0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');
-- identifier not exist
-- identifier available not enough
INSERT INTO TA_LIGNE_RECETTE(IDENTIFIANT,ACTIVITE,NATURE_ECONOMIQUE,VERSION_ACTE,AJUSTEMENT,AUDIT_ACTEUR,AUDIT_ACTION,AUDIT_DATE,AUDIT_FONCTIONNALITE) VALUES ('identifier_available_not_enough','3','1','1',0,'christian','MODIFICATION', DATE '2000-1-1','AJUSTEMENT');