CREATE TABLE "TA_PA_ACTUALISER_VM" 
   ("IDENTIFIANT" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"VM" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DATE_DEBUT" DATE NOT NULL ENABLE, 
	"DATE_FIN" DATE, 
	"MESSAGE" VARCHAR2(255 BYTE), 
	 CONSTRAINT "TA_PA_ACTUALISER_VM_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE
   );
 

